"""initial production foundation

Revision ID: d24151675ee0
Revises: 
Create Date: 2026-09-18 11:35:27.403253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd24151675ee0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_login_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    op.create_index(op.f('ix_oauth_login_states_expires_at'), 'oauth_login_states', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('primary_email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=True)
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=512), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('one_time_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_one_time_tokens_expires_at'), 'one_time_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_one_time_tokens_user_id'), 'one_time_tokens', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('csrf_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index('ix_audit_org_time', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.Enum('ORGANIZATION', 'RESTRICTED', name='documentvisibility'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'current_version_id'], ['document_versions.organization_id', 'document_versions.id'], name='fk_document_current_version', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id')
    )
    op.create_index('ix_document_org_updated', 'documents', ['organization_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_owner_user_id'), 'documents', ['owner_user_id'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('work_email', sa.String(length=320), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('manager_profile_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus'), nullable=False),
    sa.Column('profile_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'manager_profile_id'], ['employee_profiles.organization_id', 'employee_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    op.create_index('ix_employee_org_name', 'employee_profiles', ['organization_id', 'display_name'], unique=False)
    op.create_index(op.f('ix_employee_profiles_organization_id'), 'employee_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_profiles_user_id'), 'employee_profiles', ['user_id'], unique=False)
    op.create_table('organization_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', name='organizationrole'), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitation_org_email', 'organization_invitations', ['organization_id', 'normalized_email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_expires_at'), 'organization_invitations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', name='organizationrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='membershipstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_status'), 'organization_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    op.create_table('password_credentials',
    sa.Column('auth_identity_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_identity_id'], ['auth_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_identity_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('organization_id', 'slug')
    )
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('document_team_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', name='grantpermission'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'team_id'], ['teams.organization_id', 'teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'team_id')
    )
    op.create_index(op.f('ix_document_team_grants_document_id'), 'document_team_grants', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_team_grants_organization_id'), 'document_team_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_team_grants_team_id'), 'document_team_grants', ['team_id'], unique=False)
    op.create_table('document_user_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('VIEW', name='grantpermission'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id')
    )
    op.create_index(op.f('ix_document_user_grants_document_id'), 'document_user_grants', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_user_grants_organization_id'), 'document_user_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_user_grants_user_id'), 'document_user_grants', ['user_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('ingestion_status', sa.Enum('PENDING_UPLOAD', 'UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='ingestionstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0'),
    sa.CheckConstraint('version_number > 0'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number'),
    sa.UniqueConstraint('organization_id', 'id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_ingestion_status'), 'document_versions', ['ingestion_status'], unique=False)
    op.create_index(op.f('ix_document_versions_organization_id'), 'document_versions', ['organization_id'], unique=False)
    op.create_index('ix_version_org_document', 'document_versions', ['organization_id', 'document_id', 'version_number'], unique=False)
    op.create_foreign_key(
        'fk_document_current_version',
        'documents',
        'document_versions',
        ['organization_id', 'current_version_id'],
        ['organization_id', 'id'],
        ondelete='RESTRICT',
    )
    op.create_table('team_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('employee_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'employee_profile_id'], ['employee_profiles.organization_id', 'employee_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'team_id'], ['teams.organization_id', 'teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'employee_profile_id')
    )
    op.create_index(op.f('ix_team_memberships_employee_profile_id'), 'team_memberships', ['employee_profile_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_organization_id'), 'team_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_organization_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_employee_profile_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_constraint('fk_document_current_version', 'documents', type_='foreignkey')
    op.drop_index('ix_version_org_document', table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_organization_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_ingestion_status'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_user_grants_user_id'), table_name='document_user_grants')
    op.drop_index(op.f('ix_document_user_grants_organization_id'), table_name='document_user_grants')
    op.drop_index(op.f('ix_document_user_grants_document_id'), table_name='document_user_grants')
    op.drop_table('document_user_grants')
    op.drop_index(op.f('ix_document_team_grants_team_id'), table_name='document_team_grants')
    op.drop_index(op.f('ix_document_team_grants_organization_id'), table_name='document_team_grants')
    op.drop_index(op.f('ix_document_team_grants_document_id'), table_name='document_team_grants')
    op.drop_table('document_team_grants')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('password_credentials')
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_status'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_expires_at'), table_name='organization_invitations')
    op.drop_index('ix_invitation_org_email', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_index(op.f('ix_employee_profiles_user_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_organization_id'), table_name='employee_profiles')
    op.drop_index('ix_employee_org_name', table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index('ix_document_org_updated', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index('ix_audit_org_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_one_time_tokens_user_id'), table_name='one_time_tokens')
    op.drop_index(op.f('ix_one_time_tokens_expires_at'), table_name='one_time_tokens')
    op.drop_table('one_time_tokens')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_login_states_expires_at'), table_name='oauth_login_states')
    op.drop_table('oauth_login_states')
    # ### end Alembic commands ###
